### ISSUE TITLE
error in music.py

### ISSUE THREAD

**Issue by Rao2002** [JonnyBoy2000/Fresh#3]
[Music] Error during ensure_voice: No available nodes! 
![image](https://user-images.githubusercontent.com/97659314/202881001-77dd405f-6d97-4cd3-9cab-4daa9ab90db0.png)

**Comment by Jonny0181** [comment]
Have you made sure you have the lavalink config correct?
```json
"lavalink": {
    "host": "",
    "pass": "",
    "port": 2333,
    "name": "",
    "region": ""
}
```

**Comment by Jonny0181** [comment]
I pushed a example config file, you should go ahead and take a look at that.
https://github.com/Aoi-Kanzaki/Aoi-Kanzaki/blob/main/config.json.example
